### ISSUE TITLE
The controller doesnt appear in steamvr

### ISSUE THREAD

**Issue by Saimokore** [Waterdish/ARCore-VR-Controller#9]
I followed the instructions and went to connect, same wifi, same ip, but nothing shows up. Im using a Oculus rift DK2, so i dont have controllers, could you please help me?

**Comment by Waterdish** [comment]
Did you confirm that the driver is actually getting loaded in steamvr?

**Comment by Saimokore** [comment]
Is there a way to tell if its getting loaded? Cause ive tried multiple ways of putting the files in the steamvr folder and it didnt gave any sign of life

**Comment by Saimokore** [comment]
Got it to work (i was just being stupid), now the controllers are just is stuck at 0,0 (they actually move from my feet to 0,0 when i move my phone closer to the ground), the buttons work though, but not the joystick. I opened the SteamVR console says:

`Sat Aug 03 2024 14:22:00.010 [Warning] - pose.vPosition contains one or more NaNs. Discarding pose for 17 from arcore` multiple times.

Also when i start steamvr, this error shows 

`[Workshop] Failed to read action binding config for steam.overlay.250820. Path: C:\Program Files (x86)\Steam\steamapps\common\SteamVR\drivers\arcore\resources\input\{oculus}\input\legacy_bindings_touch.json`

and

`[Error] - [Workshop] Failed to read action binding config for openvr.component.vrcompositor. Path: C:\Program Files (x86)\Steam\steamapps\common\SteamVR\drivers\arcore\resources\input\vrcompositor_bindings_touch.json`

If you could tell me how you think you would fix this, or even the version of unity this project was made, i will try my best to make it work

**Comment by Waterdish** [comment]
I unfortunately don't remember what version of unity it was. A few people have let me know it's broken recently. From those errors, I think the issue would be on the driver c++ code side rather than the unity app side. If I find some time I will look into it, I just haven't touched this project in a while

**Comment by Saimokore** [comment]
Thank you very much, these moments are where i wish i could code properly. If you find something please let me know
